filetype plugin on
syntax on
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set number

call plug#begin()


Plug 'JuliaEditorSupport/julia-vim'

Plug 'kdheepak/JuliaFormatter.vim'

Plug 'airblade/vim-gitgutter'

call plug#end()


